/*
 * DRAFT - SOL005 - NSD Management Interface
 * DRAFT - SOL005 - NSD Management Interface IMPORTANT: Please note that this file might be not aligned to the current version of the ETSI Group Specification it refers to and has not been approved by the ETSI NFV ISG. In case of discrepancies the published ETSI Group Specification takes precedence. Please report bugs to https://forge.etsi.org/bugzilla/buglist.cgi?component=Nfv-Openapis 
 *
 * OpenAPI spec version: 2.4.1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package it.nextworks.composer.plugins.catalogue.elements.nsd;

import java.util.Objects;
import io.swagger.annotations.ApiModel;

import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;

/**
 * Match particular notification types. Permitted values: NsdOnBoardingNotification, NsdOnboardingFailureNotification, NsdChangeNotification, NsdDeletionNotification PnfdOnBoardingNotification, PnfdOnBoardingFailureNotification, PnfdDeletionNotification.  The permitted values of the \&quot;notificationTypes\&quot; ] attribute are spelled exactly as the names of the notification types to facilitate automated code generation systems.
 */
public enum NotificationType {
  
  NSDONBOARDINGNOTIFICATION("NsdOnBoardingNotification"),
  
  NSDONBOARDINGFAILURENOTIFICATION("NsdOnboardingFailureNotification"),
  
  NSDCHANGENOTIFICATION("NsdChangeNotification"),
  
  NSDDELETIONNOTIFICATION("NsdDeletionNotification"),
  
  PNFDONBOARDINGNOTIFICATION("PnfdOnBoardingNotification"),
  
  PNFDONBOARDINGFAILURENOTIFICATION("PnfdOnBoardingFailureNotification"),
  
  PNFDDELETIONNOTIFICATION("PnfdDeletionNotification");

  private String value;

  NotificationType(String value) {
    this.value = value;
  }

  @JsonValue
  public String getValue() {
    return value;
  }

  @Override
  public String toString() {
    return String.valueOf(value);
  }

  @JsonCreator
  public static NotificationType fromValue(String text) {
    for (NotificationType b : NotificationType.values()) {
      if (String.valueOf(b.value).equals(text)) {
        return b;
      }
    }
    return null;
  }
}

