/*
 * DRAFT - SOL005 - NSD Management Interface
 * DRAFT - SOL005 - NSD Management Interface IMPORTANT: Please note that this file might be not aligned to the current version of the ETSI Group Specification it refers to and has not been approved by the ETSI NFV ISG. In case of discrepancies the published ETSI Group Specification takes precedence. Please report bugs to https://forge.etsi.org/bugzilla/buglist.cgi?component=Nfv-Openapis
 *
 * OpenAPI spec version: 2.4.1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package it.nextworks.composer.plugins.catalogue.elements.nsd;

import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.util.Objects;

/**
 * This type represents the links to resources that an NSD management notification can contain.
 */
@ApiModel(description = "This type represents the links to resources that an NSD management notification can contain.")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-11-21T15:01:43.121+01:00")
public class NsdmLinks {
    @JsonProperty("nsdInfo")
    private String nsdInfo = null;

    @JsonProperty("subscription")
    private String subscription = null;

    public NsdmLinks nsdInfo(String nsdInfo) {
        this.nsdInfo = nsdInfo;
        return this;
    }

    /**
     * Get nsdInfo
     *
     * @return nsdInfo
     **/
    @ApiModelProperty(required = true, value = "")
    public String getNsdInfo() {
        return nsdInfo;
    }

    public void setNsdInfo(String nsdInfo) {
        this.nsdInfo = nsdInfo;
    }

    public NsdmLinks subscription(String subscription) {
        this.subscription = subscription;
        return this;
    }

    /**
     * Get subscription
     *
     * @return subscription
     **/
    @ApiModelProperty(required = true, value = "")
    public String getSubscription() {
        return subscription;
    }

    public void setSubscription(String subscription) {
        this.subscription = subscription;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        NsdmLinks nsdmLinks = (NsdmLinks) o;
        return Objects.equals(this.nsdInfo, nsdmLinks.nsdInfo) &&
            Objects.equals(this.subscription, nsdmLinks.subscription);
    }

    @Override
    public int hashCode() {
        return Objects.hash(nsdInfo, subscription);
    }


    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class NsdmLinks {\n");

        sb.append("    nsdInfo: ").append(toIndentedString(nsdInfo)).append("\n");
        sb.append("    subscription: ").append(toIndentedString(subscription)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}

