/*
 * DRAFT - SOL005 - NSD Management Interface
 * DRAFT - SOL005 - NSD Management Interface IMPORTANT: Please note that this file might be not aligned to the current version of the ETSI Group Specification it refers to and has not been approved by the ETSI NFV ISG. In case of discrepancies the published ETSI Group Specification takes precedence. Please report bugs to https://forge.etsi.org/bugzilla/buglist.cgi?component=Nfv-Openapis
 *
 * OpenAPI spec version: 2.4.1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package it.nextworks.composer.plugins.catalogue.elements.nsd;

import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.util.Objects;
import java.util.UUID;

/**
 * This type represents a response for the query PNFD operation.
 */
@ApiModel(description = "This type represents a response for the query PNFD operation.")
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-11-21T15:01:43.121+01:00")
public class PnfdInfo {
    @JsonProperty("id")
    private UUID id = null;

    @JsonProperty("pnfdId")
    private UUID pnfdId = null;

    @JsonProperty("pnfdName")
    private String pnfdName = null;

    @JsonProperty("pnfdVersion")
    private String pnfdVersion = null;

    @JsonProperty("pnfdProvider")
    private String pnfdProvider = null;

    @JsonProperty("pnfdInvariantId")
    private UUID pnfdInvariantId = null;

    @JsonProperty("pnfdOnboardingState")
    private PnfdOnboardingStateType pnfdOnboardingState = null;

    @JsonProperty("onboardingFailureDetails")
    private ProblemDetails onboardingFailureDetails = null;

    @JsonProperty("pnfdUsageState")
    private PnfdUsageStateType pnfdUsageState = null;

    @JsonProperty("userDefinedData")
    private KeyValuePairs userDefinedData = null;

    @JsonProperty("_links")
    private PnfdLinksType links = null;

    public PnfdInfo id(UUID id) {
        this.id = id;
        return this;
    }

    /**
     * Get id
     *
     * @return id
     **/
    @ApiModelProperty(required = true, value = "")
    public UUID getId() {
        return id;
    }

    public void setId(UUID id) {
        this.id = id;
    }

    public PnfdInfo pnfdId(UUID pnfdId) {
        this.pnfdId = pnfdId;
        return this;
    }

    /**
     * Get pnfdId
     *
     * @return pnfdId
     **/
    @ApiModelProperty(value = "")
    public UUID getPnfdId() {
        return pnfdId;
    }

    public void setPnfdId(UUID pnfdId) {
        this.pnfdId = pnfdId;
    }

    public PnfdInfo pnfdName(String pnfdName) {
        this.pnfdName = pnfdName;
        return this;
    }

    /**
     * Name of the onboarded PNFD. This information is copied from the PNFD content and shall be present after the PNFD content is on-boarded.
     *
     * @return pnfdName
     **/
    @ApiModelProperty(value = "Name of the onboarded PNFD. This information is copied from the PNFD content and shall be present after the PNFD content is on-boarded.")
    public String getPnfdName() {
        return pnfdName;
    }

    public void setPnfdName(String pnfdName) {
        this.pnfdName = pnfdName;
    }

    public PnfdInfo pnfdVersion(String pnfdVersion) {
        this.pnfdVersion = pnfdVersion;
        return this;
    }

    /**
     * Get pnfdVersion
     *
     * @return pnfdVersion
     **/
    @ApiModelProperty(value = "")
    public String getPnfdVersion() {
        return pnfdVersion;
    }

    public void setPnfdVersion(String pnfdVersion) {
        this.pnfdVersion = pnfdVersion;
    }

    public PnfdInfo pnfdProvider(String pnfdProvider) {
        this.pnfdProvider = pnfdProvider;
        return this;
    }

    /**
     * Provider of the onboarded PNFD. This information is copied from the PNFD content and shall be present after the PNFD content is onboarded.
     *
     * @return pnfdProvider
     **/
    @ApiModelProperty(value = "Provider of the onboarded PNFD. This information is copied from the PNFD content and shall be present after the PNFD content is onboarded.")
    public String getPnfdProvider() {
        return pnfdProvider;
    }

    public void setPnfdProvider(String pnfdProvider) {
        this.pnfdProvider = pnfdProvider;
    }

    public PnfdInfo pnfdInvariantId(UUID pnfdInvariantId) {
        this.pnfdInvariantId = pnfdInvariantId;
        return this;
    }

    /**
     * Get pnfdInvariantId
     *
     * @return pnfdInvariantId
     **/
    @ApiModelProperty(value = "")
    public UUID getPnfdInvariantId() {
        return pnfdInvariantId;
    }

    public void setPnfdInvariantId(UUID pnfdInvariantId) {
        this.pnfdInvariantId = pnfdInvariantId;
    }

    public PnfdInfo pnfdOnboardingState(PnfdOnboardingStateType pnfdOnboardingState) {
        this.pnfdOnboardingState = pnfdOnboardingState;
        return this;
    }

    /**
     * Get pnfdOnboardingState
     *
     * @return pnfdOnboardingState
     **/
    @ApiModelProperty(required = true, value = "")
    public PnfdOnboardingStateType getPnfdOnboardingState() {
        return pnfdOnboardingState;
    }

    public void setPnfdOnboardingState(PnfdOnboardingStateType pnfdOnboardingState) {
        this.pnfdOnboardingState = pnfdOnboardingState;
    }

    public PnfdInfo onboardingFailureDetails(ProblemDetails onboardingFailureDetails) {
        this.onboardingFailureDetails = onboardingFailureDetails;
        return this;
    }

    /**
     * Get onboardingFailureDetails
     *
     * @return onboardingFailureDetails
     **/
    @ApiModelProperty(value = "")
    public ProblemDetails getOnboardingFailureDetails() {
        return onboardingFailureDetails;
    }

    public void setOnboardingFailureDetails(ProblemDetails onboardingFailureDetails) {
        this.onboardingFailureDetails = onboardingFailureDetails;
    }

    public PnfdInfo pnfdUsageState(PnfdUsageStateType pnfdUsageState) {
        this.pnfdUsageState = pnfdUsageState;
        return this;
    }

    /**
     * Get pnfdUsageState
     *
     * @return pnfdUsageState
     **/
    @ApiModelProperty(required = true, value = "")
    public PnfdUsageStateType getPnfdUsageState() {
        return pnfdUsageState;
    }

    public void setPnfdUsageState(PnfdUsageStateType pnfdUsageState) {
        this.pnfdUsageState = pnfdUsageState;
    }

    public PnfdInfo userDefinedData(KeyValuePairs userDefinedData) {
        this.userDefinedData = userDefinedData;
        return this;
    }

    /**
     * Get userDefinedData
     *
     * @return userDefinedData
     **/
    @ApiModelProperty(value = "")
    public KeyValuePairs getUserDefinedData() {
        return userDefinedData;
    }

    public void setUserDefinedData(KeyValuePairs userDefinedData) {
        this.userDefinedData = userDefinedData;
    }

    public PnfdInfo links(PnfdLinksType links) {
        this.links = links;
        return this;
    }

    /**
     * Links to resources related to this resource.
     *
     * @return links
     **/
    @ApiModelProperty(required = true, value = "Links to resources related to this resource.")
    public PnfdLinksType getLinks() {
        return links;
    }

    public void setLinks(PnfdLinksType links) {
        this.links = links;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        PnfdInfo pnfdInfo = (PnfdInfo) o;
        return Objects.equals(this.id, pnfdInfo.id) &&
            Objects.equals(this.pnfdId, pnfdInfo.pnfdId) &&
            Objects.equals(this.pnfdName, pnfdInfo.pnfdName) &&
            Objects.equals(this.pnfdVersion, pnfdInfo.pnfdVersion) &&
            Objects.equals(this.pnfdProvider, pnfdInfo.pnfdProvider) &&
            Objects.equals(this.pnfdInvariantId, pnfdInfo.pnfdInvariantId) &&
            Objects.equals(this.pnfdOnboardingState, pnfdInfo.pnfdOnboardingState) &&
            Objects.equals(this.onboardingFailureDetails, pnfdInfo.onboardingFailureDetails) &&
            Objects.equals(this.pnfdUsageState, pnfdInfo.pnfdUsageState) &&
            Objects.equals(this.userDefinedData, pnfdInfo.userDefinedData) &&
            Objects.equals(this.links, pnfdInfo.links);
    }

    @Override
    public int hashCode() {
        return Objects.hash(id, pnfdId, pnfdName, pnfdVersion, pnfdProvider, pnfdInvariantId, pnfdOnboardingState, onboardingFailureDetails, pnfdUsageState, userDefinedData, links);
    }


    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class PnfdInfo {\n");

        sb.append("    id: ").append(toIndentedString(id)).append("\n");
        sb.append("    pnfdId: ").append(toIndentedString(pnfdId)).append("\n");
        sb.append("    pnfdName: ").append(toIndentedString(pnfdName)).append("\n");
        sb.append("    pnfdVersion: ").append(toIndentedString(pnfdVersion)).append("\n");
        sb.append("    pnfdProvider: ").append(toIndentedString(pnfdProvider)).append("\n");
        sb.append("    pnfdInvariantId: ").append(toIndentedString(pnfdInvariantId)).append("\n");
        sb.append("    pnfdOnboardingState: ").append(toIndentedString(pnfdOnboardingState)).append("\n");
        sb.append("    onboardingFailureDetails: ").append(toIndentedString(onboardingFailureDetails)).append("\n");
        sb.append("    pnfdUsageState: ").append(toIndentedString(pnfdUsageState)).append("\n");
        sb.append("    userDefinedData: ").append(toIndentedString(userDefinedData)).append("\n");
        sb.append("    links: ").append(toIndentedString(links)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}

