/*
 * DRAFT - SOL005 - VNF Package Management Interface
 * DRAFT - SOL005 - VNF Package Management Interface IMPORTANT: Please note that this file might be not aligned to the current version of the ETSI Group Specification it refers to and has not been approved by the ETSI NFV ISG. In case of discrepancies the published ETSI Group Specification takes precedence. Please report bugs to https://forge.etsi.org/bugzilla/buglist.cgi?component=Nfv-Openapis
 *
 * OpenAPI spec version: 2.4.1
 *
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package it.nextworks.composer.plugins.catalogue.elements.vnf;

import com.fasterxml.jackson.annotation.JsonProperty;
import io.swagger.annotations.ApiModelProperty;
import it.nextworks.composer.plugins.catalogue.elements.nsd.KeyValuePairs;

import java.util.Objects;

/**
 * VnfPackageArtifactInfo
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2018-11-21T15:10:42.557+01:00")
public class VnfPackageArtifactInfo {
    @JsonProperty("artifactPath")
    private String artifactPath = null;

    @JsonProperty("checksum")
    private String checksum = null;

    @JsonProperty("metadata")
    private KeyValuePairs metadata = null;

    public VnfPackageArtifactInfo artifactPath(String artifactPath) {
        this.artifactPath = artifactPath;
        return this;
    }

    /**
     * Get artifactPath
     *
     * @return artifactPath
     **/
    @ApiModelProperty(value = "")
    public String getArtifactPath() {
        return artifactPath;
    }

    public void setArtifactPath(String artifactPath) {
        this.artifactPath = artifactPath;
    }

    public VnfPackageArtifactInfo checksum(String checksum) {
        this.checksum = checksum;
        return this;
    }

    /**
     * Get checksum
     *
     * @return checksum
     **/
    @ApiModelProperty(value = "")
    public String getChecksum() {
        return checksum;
    }

    public void setChecksum(String checksum) {
        this.checksum = checksum;
    }

    public VnfPackageArtifactInfo metadata(KeyValuePairs metadata) {
        this.metadata = metadata;
        return this;
    }

    /**
     * Get metadata
     *
     * @return metadata
     **/
    @ApiModelProperty(value = "")
    public KeyValuePairs getMetadata() {
        return metadata;
    }

    public void setMetadata(KeyValuePairs metadata) {
        this.metadata = metadata;
    }


    @Override
    public boolean equals(java.lang.Object o) {
        if (this == o) {
            return true;
        }
        if (o == null || getClass() != o.getClass()) {
            return false;
        }
        VnfPackageArtifactInfo vnfPackageArtifactInfo = (VnfPackageArtifactInfo) o;
        return Objects.equals(this.artifactPath, vnfPackageArtifactInfo.artifactPath) &&
            Objects.equals(this.checksum, vnfPackageArtifactInfo.checksum) &&
            Objects.equals(this.metadata, vnfPackageArtifactInfo.metadata);
    }

    @Override
    public int hashCode() {
        return Objects.hash(artifactPath, checksum, metadata);
    }


    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("class VnfPackageArtifactInfo {\n");

        sb.append("    artifactPath: ").append(toIndentedString(artifactPath)).append("\n");
        sb.append("    checksum: ").append(toIndentedString(checksum)).append("\n");
        sb.append("    metadata: ").append(toIndentedString(metadata)).append("\n");
        sb.append("}");
        return sb.toString();
    }

    /**
     * Convert the given object to string with each line indented by 4 spaces
     * (except the first line).
     */
    private String toIndentedString(java.lang.Object o) {
        if (o == null) {
            return "null";
        }
        return o.toString().replace("\n", "\n    ");
    }

}

